main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    path('connexion/', views.loginPage, name="login"),
    path('connexion/failed', views.loginFailer, name="loginF"),
    path('deconnexion/', views.logoutUser, name="logout"),
    path('inscription/', views.signupPage, name="signup"),
    path('dashboard/', views.dashboardPage, name="dashboard"),
    path('recherche/', views.searchPage, name="search"),
    path('compte/', views.profilPage, name="profil"),
    path('compte/modifier', views.profilEdit, name="profil_edit"),
    path('nouvelle-demande/', views.demandCreationPage, name="demand_creation"),
    path('modifier-demande/<str:demande_sujet>', views.editCreationPage, name="demande_edit"),
    path('votre-demande/<int:pk>', views.detailPage, name="demand_detail"),
    path('categories/<str:category_name>', views.categoriesPage, name="cat_detail"),
    path('categories', views.allCategories, name="all_cat"),
]

pmr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}PMER{% endblock%}</title>
    {% block link %}{% endblock %}

    <!-- Bootstrap Icon CDN-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <!-- Bootstrap CDN-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'PMR/css/style.css' %}">
</head>
<body>
    <div class="container-fluid main">
        <!-- Navigation -->
        {% include 'layouts/nav.html' %}
        <!-- Content -->
        {% block content %}
        
        {% endblock %}
        <!-- Footer -->
        {% include 'layouts/footer.html' %}
    </div>
    
    {% block script %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'PMR/js/anime.min.js' %}"></script>
    <script src="{% static 'PMR/js/app.js' %}"></script>
</body>
</html>

templates/layouts/footer.html
<!-- Footer -->
<div class="row">
    <footer class="p-5 bg-dark text-white text-center">
        <div class="container">
            <div class="row"><p class="lead">Copyright &copy; 2022</p></div>
            <div class="row"><p>Powered by <strong>UP-SET</strong></p></div>
        </div>
    </footer>
</div>

templates/layouts/nav.html
{% load static %}
<!-- Navigation -->
<div class="row">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3 fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main:home' %}"><img src="{% static 'PMR/images/logo.svg' %}" width="50px" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu" aria-controls="navmenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item text-center">
                        <a href="{% url 'main:demand_creation' %}" class="nav-link btn background-orange text-dark">Trouver un pro</a>
                    </li>
                    <li class="nav-item text-center">
                        <a href="{% url 'main:search' %}" class="nav-link">Rechercher</a>
                    </li>
                    <li class="nav-item text-center">
                        <a href="{% url 'main:dashboard' %}" class="nav-link">Tableau de bord
                        </a>
                    </li>
                    <li class="nav-item text-center">
                        <a href="{% url 'main:profil' %}" class="nav-link">Profil</a>
                    </li>
                    <li class="nav-item text-center">
                        <a href="{% url 'main:logout' %}" class="nav-link">Deconnexion</a>
                    </li>
                    {% else %}
                    <li class="nav-item text-center">
                        <a href="{% url 'main:demand_creation' %}" class="nav-link btn background-orange text-dark">Trouver un pro</a>
                    </li>
                    <li class="nav-item text-center">
                        <a href="{% url 'main:search' %}" class="nav-link">Rechercher</a>
                    </li>
                    <li class="nav-item text-center">
                        <a href="{% url 'main:login' %}" class="nav-link">Connexion</a>
                    </li>
                    <li class="nav-item text-center">
                        <a href="{% url 'main:signup' %}" class="nav-link">Inscription</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>