main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    path('connexion/', views.loginPage, name="login"),
    path('connexion/failed', views.loginFailer, name="loginF"),
    path('deconnexion/', views.logoutUser, name="logout"),
    path('inscription/', views.signupPage, name="signup"),
    path('dashboard/', views.dashboardPage, name="dashboard"),
    path('recherche/', views.searchPage, name="search"),
    path('compte/', views.profilPage, name="profil"),
    path('compte/modifier', views.profilEdit, name="profil_edit"),
    path('nouvelle-demande/', views.demandCreationPage, name="demand_creation"),
    path('modifier-demande/<str:demande_sujet>', views.editCreationPage, name="demande_edit"),
    path('votre-demande/<int:pk>', views.detailPage, name="demand_detail"),
    path('categories/<str:category_name>', views.categoriesPage, name="cat_detail"),
    path('categories', views.allCategories, name="all_cat"),
]

pmr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class UserProfil(models.Model):
    user_profil = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    user_username = models.CharField(max_length=100, null=True)
    user_nom = models.CharField(max_length=100, null=True)
    user_prenom = models.CharField(max_length=100, null=True)
    user_adresse = models.CharField(max_length=150, null=True)
    user_email = models.EmailField(unique=True, null=True)
    user_tel = models.IntegerField(unique=True, null=True)
    user_isPro = models.BooleanField(default=False)

    def __str__(self):
        return self.user_username

    def isPro(self):
        self.user_isPro = True
        self.save()



class Category(models.Model):
    category_name = models.CharField(max_length=150)
    category_description = models.TextField()
    category_img = models.ImageField(null=True, default="cat.svg", upload_to='upload/')

    def __str__(self):
        return self.category_name


class Professionnel(models.Model):
    pro_name = models.CharField(max_length=150)
    pro_description = models.TextField()
    pro_img = models.ImageField(null=True, default="avatar.svg", upload_to='upload/')
    pro_rate = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ])
    pro_category = models.ManyToManyField(Category)

    def __str__(self):
        return self.pro_name


class Demande_client(models.Model):
    demande_sujet = models.CharField(max_length=100, null=True)
    demande_description = models.TextField(null=True)
    demande_modification = models.DateField(auto_now=True, null=True)
    demande_creation = models.DateField(auto_now_add=True, null=True)
    demande_utilisateur = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    demande_category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    demande_datevoulue = models.DateField(auto_now=True, null=True)
    demande_onGoing = models.BooleanField(default="True", null=True, blank=True)

    def __str__(self):
        return self.demande_sujet

main/forms.py
from django import forms
from main.models import Category, Professionnel, Demande_client, UserProfil
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.utils.translation import gettext_lazy as _

#Creez vos formulaire ici>

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class ProfessionnelForm(forms.ModelForm):
    class Meta:
        model = Professionnel
        fields = '__all__'


class Demande_clientForm(forms.ModelForm):

    class Meta:
        model = Demande_client
        fields = ['demande_sujet', 'demande_description', 'demande_category']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['demande_sujet'].label = "Sujet"
        self.fields['demande_description'].label = "Description"
        self.fields['demande_category'].label = "Categorie: "
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit', css_class="btn btn-success mt-3"))


class Demande_clientForm1(forms.ModelForm):

    class Meta:
        model = Demande_client
        fields = ['demande_sujet', 'demande_description', 'demande_category']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['demande_sujet'].label = "Sujet"
        self.fields['demande_description'].label = "Description"
        self.fields['demande_category'].label = "Categorie: "
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save', css_class="btn btn-success mt-3"))


class UserProfilForm(forms.ModelForm):
    class Meta:
        model = UserProfil
        fields = [ 'user_prenom', 'user_nom', 'user_tel', 'user_email', 'user_adresse']
        labels = {
            'user_prenom': _('Prenom'),
            'user_nom': _('Nom'),
            'user_tel': _('Telephone'),
            'user_email': _('Email'),
            'user_adresse': _('Adresse'),
        }
        error_messages = {
            'user_prenom': {
                'max_length': _("Ce prenom est trop long."),
            },
            'user_nom': {
                'max_length': _("Ce Nom est trop long."),
            },
            'user_tel': {
                'errors': _("Ce numero est incorrect ou deja utiliser."),
            },
            'user_email': {
                'errors': _("Cet email est incorrect ou deja utiliser."),
            },
            'user_adresse': {
                'max_length': _("Cette adresse est incorrect."),
            },
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_prenom'].label = "Prenom"
        self.fields['user_nom'].label = "Nom"
        self.fields['user_tel'].label = "Telephone"
        self.fields['user_email'].label = "Email"
        self.fields['user_adresse'].label = "Adresse"
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Enregistrer', css_class="btn btn-success mt-4"))

main/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from main.models import Professionnel, Category, Demande_client, UserProfil
from main.forms import CategoryForm, Demande_clientForm, UserProfilForm, Demande_clientForm1

# Create your views here.


def home(request):
    categories = Category.objects.all()[0:4]

    context = {
        'categories' : categories
    }
    return render(request, 'main/index.html', context)

def loginFailer(request):
    return render(request, 'main/login_fail.html')

def loginPage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:dashboard')
        else:
            return redirect('main:loginF')
    return render(request, 'main/login.html')

@login_required(login_url='main:login')
def logoutUser(request):
    logout(request)
    return redirect('main:home')

def signupPage(request):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        profilform = UserProfilForm(data=request.POST)
        if form.is_valid() and profilform.is_valid():
            user = form.save()
            profile = profilform.save(commit=False)
            profile.user_profil = user
            profile.user_username = user.username
            profile.save()
            login(request, user)
            return redirect('main:dashboard')
    else:
        form = UserCreationForm()
        profilform = UserProfilForm()
    return render(request, 'main/signup.html', {'form': form, 'profilform': profilform})

@login_required(login_url='main:login')
def dashboardPage(request):
    user = request.user
    demandes = Demande_client.objects.filter(demande_utilisateur=user).order_by('-demande_creation')
    
    context = {
        'demandes': demandes
    }
    return render(request, 'main/dashbord.html', context)

def searchPage(request):
    cat = Category.objects.all()
    catlen = len(cat)
    catt = []
    cat1 = []
    cat2 = []
    cat3 = []
    pop = False

    for i in range(catlen):
        catt.append(cat[i])

    if catlen <= 5:
        cat1 = catt
    elif catlen > 5 and catlen <= 10:
        for j in range(5):
            cat1.append(catt[j])
        for k in range(5,catlen):
            cat2.append(catt[k])
    elif catlen > 10 and catlen <= 15:
        for g in range(5):
            cat1.append(catt[g])
        for m in range(5,10):
            cat2.append(catt[m])
        for b in range(10,catlen):
            cat3.append(catt[b])
    else:
        for f in range(5):
            cat1.append(catt[f])
        for w in range(5,10):
            cat2.append(catt[w])
        for v in range(10,16):
            cat3.append(catt[v])
        pop = True
 
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    if q != '':
        categories_search = Category.objects.filter(
            Q(category_name__icontains=q) |
            Q(category_description__icontains=q)
        )
        categories_search_count = categories_search.count()
    else:
        categories_search = ''
        categories_search_count = 0

    context = {
        'categories' : categories_search,
        'categories_count' : categories_search_count,
        'cat1': cat1,
        'cat2': cat2,
        'cat3': cat3,
        'pop': pop
    }
    return render(request, 'main/recherche.html', context)

def categoriesPage(request, category_name):
    categorie = get_object_or_404(Category, category_name=category_name)
    context = {
        'categorie': categorie
    }
    return render(request, 'main/categories.html', context)


def allCategories(request):
    categories = Category.objects.all()
    context = {
        'categories' : categories
    }
    return render(request, 'main/allcategories.html', context)

@login_required(login_url='main:login')
def profilPage(request):
    user = request.user
    userprofile = UserProfil.objects.filter(user_username=request.user.username)
    demandes = Demande_client.objects.filter(demande_utilisateur=user).order_by('-demande_creation')
    
    context = {
        'demandes': demandes,
        'userprofile': userprofile
    }
    return render(request, 'main/profil.html', context)

@login_required(login_url='main:login')
def profilEdit(request):
    user = request.user
    user2 = get_object_or_404(UserProfil, user_profil=user)
    if request.method == 'POST':
        formm = UserCreationForm(request.POST, instance=user)
        form = UserProfilForm(request.POST, instance=user)
        if form.is_valid() and formm.is_valid():
            form.save()
            formm.save()
            redirect('main:profil')
    else:
        formm = UserCreationForm(instance=user)
        form = UserProfilForm(instance=user2)

    context = {
        'form1' : formm,
        'form2' : form
    }
    return render(request, 'main/profil_edit.html', context)


@login_required(login_url='main:login')
def demandCreationPage(request):

    if request.method == 'POST':
        form = Demande_clientForm(request.POST)
        if form.is_valid():
            demande = form.save(commit=False)
            demande.demande_utilisateur = request.user
            demande.save()
            return redirect('main:dashboard')
    else:
        form = Demande_clientForm()

    context = {
        'form' : form,
    }
    return render(request, 'main/demand_creation.html', context)


@login_required(login_url='main:login')
def editCreationPage(request,demande_sujet):
    demande = get_object_or_404(Demande_client, demande_sujet=demande_sujet)

    if request.method == 'POST':
        form = Demande_clientForm1(request.POST, instance=demande)
        if form.is_valid():
            form.save()
            return redirect('main:dashboard')
    else:
        form = Demande_clientForm1(instance=demande)

    context = {
        'demande': demande,
        'form' : form,
    }
    return render(request, 'main/demand_creation.html', context)


@login_required(login_url='main:login')
def detailPage(request,pk):
    demande = get_object_or_404(Demande_client, id=pk)

    context = {
        'demande': demande,
    }
    return render(request, 'main/demand-detail.html', context)

main/templates/main/allcategories.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Toutes les categories{% endblock %}
{% block content %}

        <!-- All Categories -->
        <div class="row pt-2">
            <section class="bg-dark text-light text-center pt-3">
                <div class="container">
                    <div class="row justify-content-center">  
                        <div class="col-sm-12 col-md-8">
                            <div class="login-container">
                                <h1>Toutes Nos Catégories</h1>
                                <hr>

                                <ul>
                                {% for cat in categories %}
                                    <a href="{% url 'main:cat_detail' cat.category_name %}" class="btn btn-outline-secondary"><h5>{{ cat.category_name }}</h5></a>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
{% endblock %}


        

main/templates/main/categories.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Categories | {{categorie.category_name}}{% endblock %}
{% block content %}
        <!-- Categorie -->
        <div class="row justify-content-center bg-dark">
            <div class="col-8 text-center catDetailInfo background-orange">
                <div class="row justify-content-center">
                    <h2 class="pt-5">{{categorie.category_name}}</h2>
                </div>

                <div class="row justify-content-center">
                    <p>{{categorie.category_description}}</p>
                </div>

                <div class="row justify-content-center">
                    <div class="col-5">
                        <a href="{% url 'main:demand_creation' %}" class="btn btn-outline-secondary">Creez une demande pour cette categorie.</a>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block script %}
{% endblock %}

main/templates/main/dashbord.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Tableau de Bord{% endblock %}
{% block content %}
        <!-- Content -->
        <div class="row">
            <section class="bg-dark text-light text-center pt-3">
                <div class="container-fluid dashboard-containerfluid">
                    <div class="row">
                        <div class="col-4 align-self-start left-nav-container d-none d-sm-block">
                            <div class="left-nav">
                                <h1>Profil</h1>
                                <ul>
                                    <li>{{request.user.username}}</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6 align-self-center">
                            <h1>Tableau de Bord</h1>
                            <div class="row justify-content-end">
                                <div class="col-2">
                                    <a class="add-commande-dashboard" href="{% url 'main:demand_creation' %}"><h2><i class="bi bi-clipboard-plus"></i></h2> Ajouter une Commande</a>
                                 </div>
                            </div>
                            <div class="jobs-container">
                                {% for demande in demandes %}
                                <div class="col-12 background-orange text-dark m-2 jobs-description">
                                    <div class="job-status"><h5><strong>Pending</strong></h5></div>
                                    <h2>{{demande.demande_sujet}}</h2>
                                    <p>{{demande.demande_description}}</p>
                                    <p>modifier le {{demande.demande_modification}}</p>
                                    <a href="{% url 'main:demand_detail' demande.id %}" class="btn btn-outline-primary">Voir</a>
                                    <a href="{% url 'main:demande_edit' demande.demande_sujet %}" class="btn btn-outline-danger">Modifier</a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>
{% endblock %}

main/templates/main/demand_creation.html
{% extends 'layouts/base.html'%}
{% load crispy_forms_tags %}
{% block title %}Nouvelle Demande{% endblock %}
{% block content %}
        <!-- Demand Form -->
        <div class="row">
            <section class="bg-dark text-light text-center p-5">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-8 form-demand-container">
                            <div class="form-header">
                                    <div class="form-header-back d-none d-md-block"><a href="{% url 'main:dashboard' %}"><i class="bi bi-arrow-90deg-left"></i></a></div>
                                    <div><h3>Creez une Demande</h3></div>
                            </div>
                            <div>
                                <form action="{% url 'main:demand_creation' %}" method="POST">
                                    <div class="form-demand-block">
                                        {% csrf_token %}
                                        {% crispy form %}
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
{% endblock %}

main/templates/main/demand_edit.html
{% extends 'layouts/base.html'%}
{% load crispy_forms_tags %}
{% block title %}Modifier Demande{% endblock %}
{% block content %}
        <!-- Demand Form -->
        <div class="row">
            <section class="bg-dark text-light text-center p-5">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-8 form-demand-container">
                            <div class="form-header">
                                    <div class="form-header-back d-none d-md-block"><a href="{% url 'main:dashboard' %}"><i class="bi bi-arrow-90deg-left"></i></a></div>
                                    <div><h3>Creez une Demande</h3></div>
                            </div>
                            <div>
                                <form action="{% url 'main:demande_edit' %}" method="POST">
                                    
                                    <div class="form-demand-block">
                                        {% csrf_token %}
                                        {% crispy form %}
                                    </div>
                                 
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
{% endblock %}

main/templates/main/profil.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Profil{% endblock %}
{% block content %}
        <!-- Profil -->
        <div class="row pt-2">
            <div class="container">
                <div class="row justify-content-center">
                    <section class="background-orange text-light text-center pt-3">
                        <div class="row justify-content-between">
                            <div class="col-12 profil-top-container">
                                <div class="profil-top">
                                    <a class="d-none d-lg-block" href="{% url 'main:profil_edit' %}"><i class="bi bi-journal-plus"> Modifier Profil</i></a>
                                    <a class="d-block d-lg-none" href="{% url 'main:profil_edit' %}"><i class="bi bi-journal-plus"></i></a>
                                </div>
                                <img class="img-fluid rounded-circle" src="static/images/informaticien.jpg" width="200px" alt="">
                                <h1>{{request.user.username}}</h1>
                                <p class="text-dark">Description: <br></p>
                            </div>
                        </div>
                    </section>
                </div>

                <div class="row justify-content-center">
                    <section class="bg-dark text-light text-center pt-3">
                        <div class="row justify-content-center">
                            <div class="col-md-4">
                                <h3>Mon Profil:</h3>
                                <div class="row justify-content-center pb-5">
                                    <div class="col-md-6">
                                        <div class="pt-3">
                                            <label class="col-12" for="username">Nom d'utilisateur: </label>
                                            <h5 class="text-center pt-1">{{request.user.username}}</h5>
                                        </div>
                                    {% for userprofil in userprofile %}
                                        <div class="pt-3">
                                            <label class="col-12" for="username">Nom et Prenom: </label>
                                            <h5 class="text-center pt-1">{{userprofil.user_nom}} {{userprofil.user_prenom}}</h5>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="pt-3">
                                            <label class="col-12" for="username">Telephone: </label>
                                            <h5 class="text-center pt-1">{{userprofil.user_tel}}</h5>
                                        </div>
                                        <div class="pt-3">
                                            <label class="col-12" for="username">Email: </label>
                                            <h5 class="text-center pt-1">{{userprofil.user_email}}</h5>
                                        </div>
                                        <div class="pt-3">
                                            <label class="col-12" for="username">Adresse: </label>
                                            <h5 class="text-center pt-1">{{userprofil.user_adresse}}</h5>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="col-md-4 pt-5 pt-md-0">
                                <h3>Mes parametres:</h3>
                                {% for userprofil in userprofile %}
                                    {% if userprofil.user_isPro %}
                                    <div>
                                        <input type="checkbox" checked disabled>
                                        <label>Compte Actif</label>
                                    </div>
                                    <div>
                                        <input type="checkbox" checked disabled>
                                        <label>Proffesionnel</label>
                                    </div>  
                                    {% else %}
                                    <div>
                                        <input type="checkbox" checked disabled>
                                        <label>Compte Actif</label>
                                    </div>
                                    <div>
                                        <input type="checkbox" disabled>
                                        <label>Proffesionnel</label>
                                    </div>  
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-12 pt-5 pt-md-0">
                                <h3>Historiques:</h3>
                                {% for demande in demandes %}
                                <div class="row justify-content-center">
                                    <div class="col-md-6 background-orange text-dark m-2 jobs-description">
                                        <div class="job-status"><h5><strong>Pending</strong></h5></div>
                                        <h2>{{demande.demande_sujet}}</h2>
                                        <p>{{demande.demande_description}}</p>
                                        <p>modifier le {{demande.demande_modification}}</p>
                                        <a href="{% url 'main:demand_detail' demande.id %}" class="btn btn-outline-primary">> Voir</a>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
{% endblock %}

main/templates/main/recherche.html
{% extends 'layouts/base.html'%}
{% load static %}
{% block title %}Recherche{% endblock %}
{% block content %}
        <!-- Search -->
        <div class="row">
            <section class="bg-dark text-light text-center pt-3">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12">
                            <div class="search-div">
                                <form action="{% url 'main:search' %}" method="GET" class="form-inline">
                                    <label >Rechercher une categorie: </label>
                                    <input name="q" class="searchinput searchinputcustom" type="search" placeholder="Search" aria-label="Search">
                                    <button class="btn btn-outline-success" type="submit">Search</button>
                                </form>
                                <div id="filter-btn" class=""><a class="btn btn-light"><i class="bi bi-justify lead"></i>Toutes les Categories</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section id="filter-container" class="bg-dark text-light text-center pt-3">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            {% for ca1 in cat1 %}
                            <a href="{% url 'main:cat_detail' ca1.category_name %}" class="btn btn-warning col-12">{{ca1.category_name}}</a>
                            {% endfor %}
                        </div>
                      
                        <div class="col-md-4">
                            {% for ca2 in cat2 %}
                            <a href="{% url 'main:cat_detail' ca2.category_name %}" class="btn btn-danger col-12">{{ca2.category_name}}</a>
                            {% endfor %}
                        </div>
                        
                        <div class="col-md-4">
                            {% for ca3 in cat3 %}
                            <a href="{% url 'main:cat_detail' ca3.category_name %}" class="btn btn-primary col-12">{{ca3.category_name}}</a>
                            {% endfor %}
                        </div>                        

                        {% if pop %}
                        <a href="{% url 'main:all_cat' %}" class="btn btn-success mt-4"> Voir Tout</a>
                        {% endif %}
                    </div>
                </div>
            </section>

            <section class="bg-dark text-light text-center pt-3">
                <div class="container-fluid dashboard-containerfluid">
                    <div class="row justify-content-center">
                        {% if categories != '' %}
                            {% for categorie in categories %}
                            <div class="col-md-4">
                                <div class="jobs-container">
                                    <div class="col-12 background-orange text-dark m-sm-2 jobs-description">
                                        <h2>{{categorie.category_name}}</h2>
                                        <p>{{categorie.category_description}}</p>
                                        <a href="{% url 'main:cat_detail' categorie.category_name %}" class="btn btn-outline-primary">Voir</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        {% else %}
                        <div class="col-md-4 pt-5">
                            <h2 class="pt-5">Aucune Categories...</h2>
                            <img class="img-fluid pt-2" src="{% static 'PMR/images/noresult.svg' %}" alt="Aucun resultat">
                        </div>
                        {% endif %}
                    </div>
                </div>
            </section>

        </div>
{% endblock %}

{% block script %}
    <script>
        let btn = document.querySelector('#filter-btn');
        let container = document.querySelector('#filter-container');
        let showable = false;
        function showCategory(){
            if (showable == true){
                container.style.display = "none";
                showable = false;
            }else {
                container.style.display = "block";
                showable = true;
            }
        }
        btn.addEventListener("click", function(){
            showCategory();
            console.log("Sa click");
        }, false);
    </script>
{% endblock %}